require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe Portal::ConfigsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Portal::Config. As you add validations to Portal::Config, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Portal::ConfigsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all portal_configs as @portal_configs" do
      config = Portal::Config.create! valid_attributes
      get :index, params: {}, session: valid_session
      expect(assigns(:portal_configs)).to eq([config])
    end
  end

  describe "GET #show" do
    it "assigns the requested portal_config as @portal_config" do
      config = Portal::Config.create! valid_attributes
      get :show, params: {id: config.to_param}, session: valid_session
      expect(assigns(:portal_config)).to eq(config)
    end
  end

  describe "GET #new" do
    it "assigns a new portal_config as @portal_config" do
      get :new, params: {}, session: valid_session
      expect(assigns(:portal_config)).to be_a_new(Portal::Config)
    end
  end

  describe "GET #edit" do
    it "assigns the requested portal_config as @portal_config" do
      config = Portal::Config.create! valid_attributes
      get :edit, params: {id: config.to_param}, session: valid_session
      expect(assigns(:portal_config)).to eq(config)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Portal::Config" do
        expect {
          post :create, params: {portal_config: valid_attributes}, session: valid_session
        }.to change(Portal::Config, :count).by(1)
      end

      it "assigns a newly created portal_config as @portal_config" do
        post :create, params: {portal_config: valid_attributes}, session: valid_session
        expect(assigns(:portal_config)).to be_a(Portal::Config)
        expect(assigns(:portal_config)).to be_persisted
      end

      it "redirects to the created portal_config" do
        post :create, params: {portal_config: valid_attributes}, session: valid_session
        expect(response).to redirect_to(Portal::Config.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved portal_config as @portal_config" do
        post :create, params: {portal_config: invalid_attributes}, session: valid_session
        expect(assigns(:portal_config)).to be_a_new(Portal::Config)
      end

      it "re-renders the 'new' template" do
        post :create, params: {portal_config: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested portal_config" do
        config = Portal::Config.create! valid_attributes
        put :update, params: {id: config.to_param, portal_config: new_attributes}, session: valid_session
        config.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested portal_config as @portal_config" do
        config = Portal::Config.create! valid_attributes
        put :update, params: {id: config.to_param, portal_config: valid_attributes}, session: valid_session
        expect(assigns(:portal_config)).to eq(config)
      end

      it "redirects to the portal_config" do
        config = Portal::Config.create! valid_attributes
        put :update, params: {id: config.to_param, portal_config: valid_attributes}, session: valid_session
        expect(response).to redirect_to(config)
      end
    end

    context "with invalid params" do
      it "assigns the portal_config as @portal_config" do
        config = Portal::Config.create! valid_attributes
        put :update, params: {id: config.to_param, portal_config: invalid_attributes}, session: valid_session
        expect(assigns(:portal_config)).to eq(config)
      end

      it "re-renders the 'edit' template" do
        config = Portal::Config.create! valid_attributes
        put :update, params: {id: config.to_param, portal_config: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested portal_config" do
      config = Portal::Config.create! valid_attributes
      expect {
        delete :destroy, params: {id: config.to_param}, session: valid_session
      }.to change(Portal::Config, :count).by(-1)
    end

    it "redirects to the portal_configs list" do
      config = Portal::Config.create! valid_attributes
      delete :destroy, params: {id: config.to_param}, session: valid_session
      expect(response).to redirect_to(portal_configs_url)
    end
  end

end
